### ISSUE TITLE
Reactivity does not work

### ISSUE THREAD

**Issue by akaiworld** [ccorcos/meteor-any-db#11]
I use neo4j-fiber with ccorcos:any-db.
Here is my code:

SERVER: 
let c = db.query({
cypher:  MATCH (node) RETURN node.id as _id, node.id, node.topic , 
reactive: true, 
});
AnyDb.publish('allNodes', ( data ) => {
return c.fetch();
});

CLIENT: 
Session.set('nodes', 'loading');
let subscripiton = AnyDb.subscribe('allNodes', {data: 'AKAI'}, ( sub ) => {
    log("sub ready");
    Session.set('nodes', sub.data);
    sub.onChange( (data) => {
        log("new sub data")
        Session.set('nodes', data);
    });
}); 
export default createContainer(() => {
    return {
        nodes: Session.get('nodes'), 
    };
}, EventsListPage);

Data is fetched only once, but when i add some nodes to the DB directly - nothing updates reactivelly. Only when i refresh the page data does update.

Actually i do not know where it is better to ask, i already asked this question here https://github.com/VeliovGroup/neo4j-fiber/issues/2
but hope you can help me. 
Thanks

**Comment by ccorcos** [comment]
> when i add some nodes to the DB directly - nothing updates reactivelly. 

thats expected. databases store data. their purpose isnt to handle reactivity. thats the responsibility of the system thats writing to the database. 

although redis, rethinkdb, and to some extend mongo (with oplog tailing) have reactivity baked in, its not an ideal solution. databases arent going to be the best for this kind of thing because they cant optimize for your situations. they will never be able to handle generalized aggregation queries efficiently, and will cripple under the complexity of highly relational queries. 

thats why i think any-db and feathers.js (a much better implementation of the same concept) is on the right path. databases are for storage and efficient lookup. but its up to your system to handle reactivity. 

imagine how iMessage or WhatsApp works. a single computer cant handle distributing all the messages sent at every moment. thus you need to do things like, for example, hash the userId and distribute the load to multiple machines. This isnt something that a database can do because it has not idea what your architecture is.

hope that helps :)

**Comment by dr-dimitru** [comment]
Actually same behaviour may be found in [Neo4jreactivity](https://github.com/VeliovGroup/ostrio-Neo4jreactivity). As we can not watch actions made outside of the driver.

Also you can read [this article](http://neo4j.com/news/meteor-any-database)

**Comment by akaiworld** [comment]
dr-dimitru, actually this worked fine with Neo4jreactivity for me, but not with neo4j-fiber. Btw thanks for the article. 

ccorcos, i understand that, thanks for the detailed info. But the data in the "c" variable is reactive, according to the dr-dimitru's neo4j-fiber package. So as i understand reactivity should work. But it does not. 

For this is not a big problem, cause, using methods reactivity works fine. But it is better to make all things work...

Btw, ccorcos, i liked the feathersjs framework, but not sure whether to switch to it, cause it is similar to meteor, but seems to be less mature accourding to github stars. Maybe i'am not right...

**Comment by dr-dimitru** [comment]
One note from me: _yes it is reactive, as long as you use it on the Server_.

> The _reactive_ feature in [neo4j-fiber](https://github.com/VeliovGroup/neo4j-fiber) allows to update data, which may be changed during runtime.

**Comment by akaiworld** [comment]
dr-dimitru, that's right. This is server code:

let c = db.query({
cypher: MATCH (node) RETURN node.id as _id, node.id, node.topic , 
reactive: true, 
});
AnyDb.publish('allNodes', ( data ) => {
return c.fetch();
});

Also tried this way:
AnyDb.publish('allNodes', ( data ) => {
let c = db.query({
cypher: MATCH (node) RETURN node.id as _id, node.id, node.topic , 
reactive: true, 
});
return c.fetch();
});

**Comment by ccorcos** [comment]
Neo4jreactivity polls and writes to mongo. its not a realistic solution for most apps

**Comment by dr-dimitru** [comment]
Agree with @ccorcos
That's why neo4jReactivity is not in stable release and I recommend to use neo4j-fiber

**Comment by akaiworld** [comment]
The code above is already for neo4j-fiber + ccorcos:any-db

**Comment by ccorcos** [comment]
neo4j-fiber is a "Neo4j REST API Driver" so its not _reactive_ in the same way Mongo is.
